# See https://mkosi.systemd.io/ for documentation.

[Build]
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.build

[Output]
Format=directory

[Build]
ToolsTree=default
Incremental=yes
BuildSources=.
ToolsTreePackages=
        cargo
        cargo-rpm-macros
        clang
        gnupg-pkcs11-scd
        kryoptic
        opensc
        openssl-devel
        pesign
        pkcs11-provider
        pkg-config
        rpm-build
        sequoia-sq
        softhsm
        sqlite-devel

[Content]
Locale=C.UTF-8
Bootable=yes
Autologin=yes
SELinuxRelabel=no
KernelCommandLine=
        selinux=0
        systemd.firstboot=no

Packages=
        acl
        attr
        bash
        bash-completion
        binutils
        curl
        findutils
        gdb
        grep
        jq
        less
        nmap-nc
        opensc
        openssl
        p11-kit
        python3
        sed
        socat
        strace
        swtpm
        systemd
        tar
        tree
        util-linux
        vim-common
        which

[Runtime]
RAM=2G
CPUs=2
TPM=yes
VSock=yes
KVM=yes
RuntimeBuildSources=yes
