// SPDX-License-Identifier: MIT
// Copyright (c) Microsoft Corporation.

//! Function tables for the PKCS#11 2.40, 3.0, and 3.2 specifications.
//!
//! These are, for the most part, unimplemented, as this PKCS#11 module is intended to only support
//! enough of the interface for signing operations.
use crate::session::{C_CloseAllSessions, C_CloseSession, C_GetSessionInfo, C_OpenSession};
use crate::sign::{C_Sign, C_SignFinal, C_SignInit, C_SignUpdate};
use crate::{
    C_Finalize, C_FindObjects, C_FindObjectsFinal, C_FindObjectsInit, C_GetAttributeValue,
    C_GetFunctionList, C_GetInfo, C_GetInfo_3_0, C_GetInfo_3_2, C_GetInterface, C_GetInterfaceList,
    C_GetMechanismInfo, C_GetMechanismList, C_GetSlotInfo, C_GetSlotList, C_GetTokenInfo,
    C_Initialize, C_Login, C_Logout, unsupported,
};
use cryptoki_sys::{
    CK_FUNCTION_LIST, CK_FUNCTION_LIST_3_0, CK_FUNCTION_LIST_3_2, CK_INTERFACE, CK_UTF8CHAR_PTR,
    CK_VERSION, CK_VOID_PTR,
};

pub(crate) static FUNCTIONS_NAME: &std::ffi::CStr = c"PKCS 11";

static FUNCTIONS_3_2: CK_FUNCTION_LIST_3_2 = CK_FUNCTION_LIST_3_2 {
    version: CK_VERSION { major: 3, minor: 2 },
    C_Initialize: Some(C_Initialize),
    C_Finalize: Some(C_Finalize),
    C_GetInfo: Some(C_GetInfo_3_2),
    C_GetFunctionList: Some(C_GetFunctionList),
    C_GetSlotList: Some(C_GetSlotList),
    C_GetSlotInfo: Some(C_GetSlotInfo),
    C_GetTokenInfo: Some(C_GetTokenInfo),
    C_GetMechanismList: Some(C_GetMechanismList),
    C_GetMechanismInfo: Some(C_GetMechanismInfo),
    C_InitToken: Some(unsupported::C_InitToken),
    C_InitPIN: Some(unsupported::C_InitPIN),
    C_SetPIN: Some(unsupported::C_SetPIN),
    C_OpenSession: Some(C_OpenSession),
    C_CloseSession: Some(C_CloseSession),
    C_CloseAllSessions: Some(C_CloseAllSessions),
    C_GetSessionInfo: Some(C_GetSessionInfo),
    C_GetOperationState: Some(unsupported::C_GetOperationState),
    C_SetOperationState: Some(unsupported::C_SetOperationState),
    C_Login: Some(C_Login),
    C_Logout: Some(C_Logout),
    C_CreateObject: Some(unsupported::C_CreateObject),
    C_CopyObject: Some(unsupported::C_CopyObject),
    C_DestroyObject: Some(unsupported::C_DestroyObject),
    C_GetObjectSize: Some(unsupported::C_GetObjectSize),
    C_GetAttributeValue: Some(C_GetAttributeValue),
    C_SetAttributeValue: Some(unsupported::C_SetAttributeValue),
    C_FindObjectsInit: Some(C_FindObjectsInit),
    C_FindObjects: Some(C_FindObjects),
    C_FindObjectsFinal: Some(C_FindObjectsFinal),
    C_EncryptInit: Some(unsupported::C_EncryptInit),
    C_Encrypt: Some(unsupported::C_Encrypt),
    C_EncryptUpdate: Some(unsupported::C_EncryptUpdate),
    C_EncryptFinal: Some(unsupported::C_EncryptFinal),
    C_DecryptInit: Some(unsupported::C_DecryptInit),
    C_Decrypt: Some(unsupported::C_Decrypt),
    C_DecryptUpdate: Some(unsupported::C_DecryptUpdate),
    C_DecryptFinal: Some(unsupported::C_DecryptFinal),
    C_DigestInit: Some(unsupported::C_DigestInit),
    C_Digest: Some(unsupported::C_Digest),
    C_DigestUpdate: Some(unsupported::C_DigestUpdate),
    C_DigestKey: Some(unsupported::C_DigestKey),
    C_DigestFinal: Some(unsupported::C_DigestFinal),
    C_SignInit: Some(C_SignInit),
    C_Sign: Some(C_Sign),
    C_SignUpdate: Some(C_SignUpdate),
    C_SignFinal: Some(C_SignFinal),
    C_SignRecoverInit: Some(unsupported::C_SignRecoverInit),
    C_SignRecover: Some(unsupported::C_SignRecover),
    C_VerifyInit: Some(unsupported::C_VerifyInit),
    C_Verify: Some(unsupported::C_Verify),
    C_VerifyUpdate: Some(unsupported::C_VerifyUpdate),
    C_VerifyFinal: Some(unsupported::C_VerifyFinal),
    C_VerifyRecoverInit: Some(unsupported::C_VerifyRecoverInit),
    C_VerifyRecover: Some(unsupported::C_VerifyRecover),
    C_DigestEncryptUpdate: Some(unsupported::C_DigestEncryptUpdate),
    C_DecryptDigestUpdate: Some(unsupported::C_DecryptDigestUpdate),
    C_SignEncryptUpdate: Some(unsupported::C_SignEncryptUpdate),
    C_DecryptVerifyUpdate: Some(unsupported::C_DecryptVerifyUpdate),
    C_GenerateKey: Some(unsupported::C_GenerateKey),
    C_GenerateKeyPair: Some(unsupported::C_GenerateKeyPair),
    C_WrapKey: Some(unsupported::C_WrapKey),
    C_UnwrapKey: Some(unsupported::C_UnwrapKey),
    C_DeriveKey: Some(unsupported::C_DeriveKey),
    C_SeedRandom: Some(unsupported::C_SeedRandom),
    C_GenerateRandom: Some(unsupported::C_GenerateRandom),
    C_GetFunctionStatus: Some(unsupported::C_GetFunctionStatus),
    C_CancelFunction: Some(unsupported::C_CancelFunction),
    C_WaitForSlotEvent: Some(unsupported::C_WaitForSlotEvent),
    C_GetInterfaceList: Some(C_GetInterfaceList),
    C_GetInterface: Some(C_GetInterface),
    C_LoginUser: Some(unsupported::C_LoginUser),
    C_SessionCancel: Some(unsupported::C_SessionCancel),
    C_MessageEncryptInit: Some(unsupported::C_MessageEncryptInit),
    C_EncryptMessage: Some(unsupported::C_EncryptMessage),
    C_EncryptMessageBegin: Some(unsupported::C_EncryptMessageBegin),
    C_EncryptMessageNext: Some(unsupported::C_EncryptMessageNext),
    C_MessageEncryptFinal: Some(unsupported::C_MessageEncryptFinal),
    C_MessageDecryptInit: Some(unsupported::C_MessageDecryptInit),
    C_DecryptMessage: Some(unsupported::C_DecryptMessage),
    C_DecryptMessageBegin: Some(unsupported::C_DecryptMessageBegin),
    C_DecryptMessageNext: Some(unsupported::C_DecryptMessageNext),
    C_MessageDecryptFinal: Some(unsupported::C_MessageDecryptFinal),
    C_MessageSignInit: Some(unsupported::C_MessageSignInit),
    C_SignMessage: Some(unsupported::C_SignMessage),
    C_SignMessageBegin: Some(unsupported::C_SignMessageBegin),
    C_SignMessageNext: Some(unsupported::C_SignMessageNext),
    C_MessageSignFinal: Some(unsupported::C_MessageSignFinal),
    C_MessageVerifyInit: Some(unsupported::C_MessageVerifyInit),
    C_VerifyMessage: Some(unsupported::C_VerifyMessage),
    C_VerifyMessageBegin: Some(unsupported::C_VerifyMessageBegin),
    C_VerifyMessageNext: Some(unsupported::C_VerifyMessageNext),
    C_MessageVerifyFinal: Some(unsupported::C_MessageVerifyFinal),
    C_EncapsulateKey: Some(unsupported::C_EncapsulateKey),
    C_DecapsulateKey: Some(unsupported::C_DecapsulateKey),
    C_VerifySignatureInit: Some(unsupported::C_VerifySignatureInit),
    C_VerifySignature: Some(unsupported::C_VerifySignature),
    C_VerifySignatureUpdate: Some(unsupported::C_VerifySignatureUpdate),
    C_VerifySignatureFinal: Some(unsupported::C_VerifySignatureFinal),
    C_GetSessionValidationFlags: Some(unsupported::C_GetSessionValidationFlags),
    C_AsyncComplete: Some(unsupported::C_AsyncComplete),
    C_AsyncGetID: Some(unsupported::C_AsyncGetID),
    C_AsyncJoin: Some(unsupported::C_AsyncJoin),
    C_WrapKeyAuthenticated: Some(unsupported::C_WrapKeyAuthenticated),
    C_UnwrapKeyAuthenticated: Some(unsupported::C_UnwrapKeyAuthenticated),
};

static FUNCTIONS_3_0: CK_FUNCTION_LIST_3_0 = CK_FUNCTION_LIST_3_0 {
    version: CK_VERSION { major: 3, minor: 0 },
    C_Initialize: Some(C_Initialize),
    C_Finalize: Some(C_Finalize),
    C_GetInfo: Some(C_GetInfo_3_0),
    C_GetFunctionList: Some(C_GetFunctionList),
    C_GetSlotList: Some(C_GetSlotList),
    C_GetSlotInfo: Some(C_GetSlotInfo),
    C_GetTokenInfo: Some(C_GetTokenInfo),
    C_GetMechanismList: Some(C_GetMechanismList),
    C_GetMechanismInfo: Some(C_GetMechanismInfo),
    C_InitToken: Some(unsupported::C_InitToken),
    C_InitPIN: Some(unsupported::C_InitPIN),
    C_SetPIN: Some(unsupported::C_SetPIN),
    C_OpenSession: Some(C_OpenSession),
    C_CloseSession: Some(C_CloseSession),
    C_CloseAllSessions: Some(C_CloseAllSessions),
    C_GetSessionInfo: Some(C_GetSessionInfo),
    C_GetOperationState: Some(unsupported::C_GetOperationState),
    C_SetOperationState: Some(unsupported::C_SetOperationState),
    C_Login: Some(C_Login),
    C_Logout: Some(C_Logout),
    C_CreateObject: Some(unsupported::C_CreateObject),
    C_CopyObject: Some(unsupported::C_CopyObject),
    C_DestroyObject: Some(unsupported::C_DestroyObject),
    C_GetObjectSize: Some(unsupported::C_GetObjectSize),
    C_GetAttributeValue: Some(C_GetAttributeValue),
    C_SetAttributeValue: Some(unsupported::C_SetAttributeValue),
    C_FindObjectsInit: Some(C_FindObjectsInit),
    C_FindObjects: Some(C_FindObjects),
    C_FindObjectsFinal: Some(C_FindObjectsFinal),
    C_EncryptInit: Some(unsupported::C_EncryptInit),
    C_Encrypt: Some(unsupported::C_Encrypt),
    C_EncryptUpdate: Some(unsupported::C_EncryptUpdate),
    C_EncryptFinal: Some(unsupported::C_EncryptFinal),
    C_DecryptInit: Some(unsupported::C_DecryptInit),
    C_Decrypt: Some(unsupported::C_Decrypt),
    C_DecryptUpdate: Some(unsupported::C_DecryptUpdate),
    C_DecryptFinal: Some(unsupported::C_DecryptFinal),
    C_DigestInit: Some(unsupported::C_DigestInit),
    C_Digest: Some(unsupported::C_Digest),
    C_DigestUpdate: Some(unsupported::C_DigestUpdate),
    C_DigestKey: Some(unsupported::C_DigestKey),
    C_DigestFinal: Some(unsupported::C_DigestFinal),
    C_SignInit: Some(C_SignInit),
    C_Sign: Some(C_Sign),
    C_SignUpdate: Some(C_SignUpdate),
    C_SignFinal: Some(C_SignFinal),
    C_SignRecoverInit: Some(unsupported::C_SignRecoverInit),
    C_SignRecover: Some(unsupported::C_SignRecover),
    C_VerifyInit: Some(unsupported::C_VerifyInit),
    C_Verify: Some(unsupported::C_Verify),
    C_VerifyUpdate: Some(unsupported::C_VerifyUpdate),
    C_VerifyFinal: Some(unsupported::C_VerifyFinal),
    C_VerifyRecoverInit: Some(unsupported::C_VerifyRecoverInit),
    C_VerifyRecover: Some(unsupported::C_VerifyRecover),
    C_DigestEncryptUpdate: Some(unsupported::C_DigestEncryptUpdate),
    C_DecryptDigestUpdate: Some(unsupported::C_DecryptDigestUpdate),
    C_SignEncryptUpdate: Some(unsupported::C_SignEncryptUpdate),
    C_DecryptVerifyUpdate: Some(unsupported::C_DecryptVerifyUpdate),
    C_GenerateKey: Some(unsupported::C_GenerateKey),
    C_GenerateKeyPair: Some(unsupported::C_GenerateKeyPair),
    C_WrapKey: Some(unsupported::C_WrapKey),
    C_UnwrapKey: Some(unsupported::C_UnwrapKey),
    C_DeriveKey: Some(unsupported::C_DeriveKey),
    C_SeedRandom: Some(unsupported::C_SeedRandom),
    C_GenerateRandom: Some(unsupported::C_GenerateRandom),
    C_GetFunctionStatus: Some(unsupported::C_GetFunctionStatus),
    C_CancelFunction: Some(unsupported::C_CancelFunction),
    C_WaitForSlotEvent: Some(unsupported::C_WaitForSlotEvent),
    C_GetInterfaceList: Some(C_GetInterfaceList),
    C_GetInterface: Some(C_GetInterface),
    C_LoginUser: Some(unsupported::C_LoginUser),
    C_SessionCancel: Some(unsupported::C_SessionCancel),
    C_MessageEncryptInit: Some(unsupported::C_MessageEncryptInit),
    C_EncryptMessage: Some(unsupported::C_EncryptMessage),
    C_EncryptMessageBegin: Some(unsupported::C_EncryptMessageBegin),
    C_EncryptMessageNext: Some(unsupported::C_EncryptMessageNext),
    C_MessageEncryptFinal: Some(unsupported::C_MessageEncryptFinal),
    C_MessageDecryptInit: Some(unsupported::C_MessageDecryptInit),
    C_DecryptMessage: Some(unsupported::C_DecryptMessage),
    C_DecryptMessageBegin: Some(unsupported::C_DecryptMessageBegin),
    C_DecryptMessageNext: Some(unsupported::C_DecryptMessageNext),
    C_MessageDecryptFinal: Some(unsupported::C_MessageDecryptFinal),
    C_MessageSignInit: Some(unsupported::C_MessageSignInit),
    C_SignMessage: Some(unsupported::C_SignMessage),
    C_SignMessageBegin: Some(unsupported::C_SignMessageBegin),
    C_SignMessageNext: Some(unsupported::C_SignMessageNext),
    C_MessageSignFinal: Some(unsupported::C_MessageSignFinal),
    C_MessageVerifyInit: Some(unsupported::C_MessageVerifyInit),
    C_VerifyMessage: Some(unsupported::C_VerifyMessage),
    C_VerifyMessageBegin: Some(unsupported::C_VerifyMessageBegin),
    C_VerifyMessageNext: Some(unsupported::C_VerifyMessageNext),
    C_MessageVerifyFinal: Some(unsupported::C_MessageVerifyFinal),
};

pub static FUNCTIONS: CK_FUNCTION_LIST = CK_FUNCTION_LIST {
    version: CK_VERSION {
        major: 2,
        minor: 40,
    },
    C_Initialize: Some(C_Initialize),
    C_Finalize: Some(C_Finalize),
    C_GetInfo: Some(C_GetInfo),
    C_GetFunctionList: Some(C_GetFunctionList),
    C_GetSlotList: Some(C_GetSlotList),
    C_GetSlotInfo: Some(C_GetSlotInfo),
    C_GetTokenInfo: Some(C_GetTokenInfo),
    C_GetMechanismList: Some(C_GetMechanismList),
    C_GetMechanismInfo: Some(C_GetMechanismInfo),
    C_InitToken: Some(unsupported::C_InitToken),
    C_InitPIN: Some(unsupported::C_InitPIN),
    C_SetPIN: Some(unsupported::C_SetPIN),
    C_OpenSession: Some(C_OpenSession),
    C_CloseSession: Some(C_CloseSession),
    C_CloseAllSessions: Some(C_CloseAllSessions),
    C_GetSessionInfo: Some(C_GetSessionInfo),
    C_GetOperationState: Some(unsupported::C_GetOperationState),
    C_SetOperationState: Some(unsupported::C_SetOperationState),
    C_Login: Some(C_Login),
    C_Logout: Some(C_Logout),
    C_CreateObject: Some(unsupported::C_CreateObject),
    C_CopyObject: Some(unsupported::C_CopyObject),
    C_DestroyObject: Some(unsupported::C_DestroyObject),
    C_GetObjectSize: Some(unsupported::C_GetObjectSize),
    C_GetAttributeValue: Some(C_GetAttributeValue),
    C_SetAttributeValue: Some(unsupported::C_SetAttributeValue),
    C_FindObjectsInit: Some(C_FindObjectsInit),
    C_FindObjects: Some(C_FindObjects),
    C_FindObjectsFinal: Some(C_FindObjectsFinal),
    C_EncryptInit: Some(unsupported::C_EncryptInit),
    C_Encrypt: Some(unsupported::C_Encrypt),
    C_EncryptUpdate: Some(unsupported::C_EncryptUpdate),
    C_EncryptFinal: Some(unsupported::C_EncryptFinal),
    C_DecryptInit: Some(unsupported::C_DecryptInit),
    C_Decrypt: Some(unsupported::C_Decrypt),
    C_DecryptUpdate: Some(unsupported::C_DecryptUpdate),
    C_DecryptFinal: Some(unsupported::C_DecryptFinal),
    C_DigestInit: Some(unsupported::C_DigestInit),
    C_Digest: Some(unsupported::C_Digest),
    C_DigestUpdate: Some(unsupported::C_DigestUpdate),
    C_DigestKey: Some(unsupported::C_DigestKey),
    C_DigestFinal: Some(unsupported::C_DigestFinal),
    C_SignInit: Some(C_SignInit),
    C_Sign: Some(C_Sign),
    C_SignUpdate: Some(C_SignUpdate),
    C_SignFinal: Some(C_SignFinal),
    C_SignRecoverInit: Some(unsupported::C_SignRecoverInit),
    C_SignRecover: Some(unsupported::C_SignRecover),
    C_VerifyInit: Some(unsupported::C_VerifyInit),
    C_Verify: Some(unsupported::C_Verify),
    C_VerifyUpdate: Some(unsupported::C_VerifyUpdate),
    C_VerifyFinal: Some(unsupported::C_VerifyFinal),
    C_VerifyRecoverInit: Some(unsupported::C_VerifyRecoverInit),
    C_VerifyRecover: Some(unsupported::C_VerifyRecover),
    C_DigestEncryptUpdate: Some(unsupported::C_DigestEncryptUpdate),
    C_DecryptDigestUpdate: Some(unsupported::C_DecryptDigestUpdate),
    C_SignEncryptUpdate: Some(unsupported::C_SignEncryptUpdate),
    C_DecryptVerifyUpdate: Some(unsupported::C_DecryptVerifyUpdate),
    C_GenerateKey: Some(unsupported::C_GenerateKey),
    C_GenerateKeyPair: Some(unsupported::C_GenerateKeyPair),
    C_WrapKey: Some(unsupported::C_WrapKey),
    C_UnwrapKey: Some(unsupported::C_UnwrapKey),
    C_DeriveKey: Some(unsupported::C_DeriveKey),
    C_SeedRandom: Some(unsupported::C_SeedRandom),
    C_GenerateRandom: Some(unsupported::C_GenerateRandom),
    C_GetFunctionStatus: Some(unsupported::C_GetFunctionStatus),
    C_CancelFunction: Some(unsupported::C_CancelFunction),
    C_WaitForSlotEvent: Some(unsupported::C_WaitForSlotEvent),
};

/// A sendable newtype for [`CK_INTERFACE`]
///
/// This is exposed to the world via static constants so it's safe to send between threads.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub(crate) struct SendableCkInterface(CK_INTERFACE);
// SAFETY: This structure is only available via statics which are guaranteed to be initialized and read-only.
unsafe impl Sync for SendableCkInterface {}
// SAFETY: This structure is only available via statics which are guaranteed to be initialized and read-only.
unsafe impl Send for SendableCkInterface {}

impl From<CK_INTERFACE> for SendableCkInterface {
    fn from(value: CK_INTERFACE) -> Self {
        Self(value)
    }
}

impl std::ops::Deref for SendableCkInterface {
    type Target = CK_INTERFACE;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

pub(crate) static INTERFACE_2_40: SendableCkInterface = SendableCkInterface(CK_INTERFACE {
    pInterfaceName: FUNCTIONS_NAME.as_ptr() as CK_UTF8CHAR_PTR,
    pFunctionList: &FUNCTIONS as *const CK_FUNCTION_LIST as CK_VOID_PTR,
    flags: 0,
});
pub(crate) static INTERFACE_3_0: SendableCkInterface = SendableCkInterface(CK_INTERFACE {
    pInterfaceName: FUNCTIONS_NAME.as_ptr() as CK_UTF8CHAR_PTR,
    pFunctionList: &FUNCTIONS_3_0 as *const CK_FUNCTION_LIST_3_0 as CK_VOID_PTR,
    flags: 0,
});
pub(crate) static INTERFACE_3_2: SendableCkInterface = SendableCkInterface(CK_INTERFACE {
    pInterfaceName: FUNCTIONS_NAME.as_ptr() as CK_UTF8CHAR_PTR,
    pFunctionList: &FUNCTIONS_3_2 as *const CK_FUNCTION_LIST_3_2 as CK_VOID_PTR,
    flags: 0,
});

pub(crate) static INTERFACES: &[SendableCkInterface] =
    &[INTERFACE_2_40, INTERFACE_3_0, INTERFACE_3_2];
